volumes:
  uploads:


services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
    ports:
      - "3308:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    hostname: hotel-rabbit
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672

  mailservice:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./hotel/MailService/Dockerfile
    depends_on:
      - rabbitmq

  authservice:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./hotel/AuthService/Dockerfile
    depends_on:
      - mysql
      - rabbitmq
      - mailservice

  roomservice:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./hotel/RoomService/Dockerfile
    depends_on:
      - mysql
      - rabbitmq

  main:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./hotel/main/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - uploads:/app/Uploads
    depends_on:
      - mysql
      - rabbitmq
      - authservice
      - roomservice
